all:
	gcc -g -c ed/ilist.c -o ed/ilist.o
	gcc -g -c ed/hashtable_ed.c -o ed/hashtable_ed.o
	gcc -g -o ed/main ed/main.c ed/ilist.o ed/hashtable_ed.o
	# gcc -g -c prime_list.c
	# gcc -g -c hashtable_ea.c
	# gcc -g prime_list_test.c -o prime_list_test prime_list.o
	# gcc -g -c utils.c
	# gcc -g embaralhar_test.c -o embaralhar_test utils.o
	# gcc -g main.c -o main ilist.o prime_list.o hashtable_ea.o utils.o
