all:
	gcc -c utils.c
	gcc -o 1_k_maior 1_k_maior.c utils.o
	gcc -o 2_sao_anagramas 2_sao_anagramas.c utils.o
	gcc -o 3_mais_frequente 3_mais_frequente.c utils.o
	gcc -o 4_remover_duplicatas 4_remover_duplicatas.c utils.o
